/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.netbeans.modules.signer.gui;

import java.awt.EventQueue;
import org.netbeans.modules.signer.core.Keystore;

/**
 * It builds "dname" parameter for a new keystore:<br><br>
 *
 * <u>-dname &lt;CN=fullName, OU=organizationUnit, O=organization, L=location,
 * ST=state, C=countryCode&gt;</u>
 *
 * @author elcocolio
 */
public class DistinguishedNameBuilderDialog extends javax.swing.JDialog {

  private final Keystore.DistinguishedName dname;

  /**
   * Creates new form DistinguishedNameDialog
   *
   * @param parent
   */
  public DistinguishedNameBuilderDialog(javax.swing.JDialog parent) {
    super(parent, true);
    initComponents();
    this.setResizable(true);
    this.dname = Keystore.createKeystore().getDistinguishedName();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jPanel1 = new javax.swing.JPanel();
    jLabel1 = new javax.swing.JLabel();
    jTxtFullName = new javax.swing.JTextField();
    jPanel2 = new javax.swing.JPanel();
    jLabel2 = new javax.swing.JLabel();
    jTxtOrganizationUnit = new javax.swing.JTextField();
    jPanel3 = new javax.swing.JPanel();
    jLabel3 = new javax.swing.JLabel();
    jTxtOrganization = new javax.swing.JTextField();
    jPanel4 = new javax.swing.JPanel();
    jLabel4 = new javax.swing.JLabel();
    jTxtLocation = new javax.swing.JTextField();
    jPanel5 = new javax.swing.JPanel();
    jLabel5 = new javax.swing.JLabel();
    jTxtState = new javax.swing.JTextField();
    jPanel6 = new javax.swing.JPanel();
    jLabel6 = new javax.swing.JLabel();
    jTxtCountryCode = new javax.swing.JTextField();
    jPanel7 = new javax.swing.JPanel();
    jBtnCompleteDname = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    getContentPane().setLayout(new java.awt.GridLayout(7, 2));

    jPanel1.setLayout(new java.awt.BorderLayout());

    org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(DistinguishedNameBuilderDialog.class, "DistinguishedNameBuilderDialog.jLabel1.text")); // NOI18N
    jLabel1.setPreferredSize(new java.awt.Dimension(100, 14));
    jPanel1.add(jLabel1, java.awt.BorderLayout.LINE_START);

    jTxtFullName.setText(org.openide.util.NbBundle.getMessage(DistinguishedNameBuilderDialog.class, "DistinguishedNameBuilderDialog.jTxtFullName.text")); // NOI18N
    jPanel1.add(jTxtFullName, java.awt.BorderLayout.CENTER);

    getContentPane().add(jPanel1);

    jPanel2.setLayout(new java.awt.BorderLayout());

    org.openide.awt.Mnemonics.setLocalizedText(jLabel2, org.openide.util.NbBundle.getMessage(DistinguishedNameBuilderDialog.class, "DistinguishedNameBuilderDialog.jLabel2.text")); // NOI18N
    jLabel2.setPreferredSize(new java.awt.Dimension(100, 14));
    jPanel2.add(jLabel2, java.awt.BorderLayout.LINE_START);

    jTxtOrganizationUnit.setText(org.openide.util.NbBundle.getMessage(DistinguishedNameBuilderDialog.class, "DistinguishedNameBuilderDialog.jTxtOrganizationUnit.text")); // NOI18N
    jPanel2.add(jTxtOrganizationUnit, java.awt.BorderLayout.CENTER);

    getContentPane().add(jPanel2);

    jPanel3.setLayout(new java.awt.BorderLayout());

    org.openide.awt.Mnemonics.setLocalizedText(jLabel3, org.openide.util.NbBundle.getMessage(DistinguishedNameBuilderDialog.class, "DistinguishedNameBuilderDialog.jLabel3.text")); // NOI18N
    jLabel3.setPreferredSize(new java.awt.Dimension(100, 14));
    jPanel3.add(jLabel3, java.awt.BorderLayout.LINE_START);

    jTxtOrganization.setText(org.openide.util.NbBundle.getMessage(DistinguishedNameBuilderDialog.class, "DistinguishedNameBuilderDialog.jTxtOrganization.text")); // NOI18N
    jPanel3.add(jTxtOrganization, java.awt.BorderLayout.CENTER);

    getContentPane().add(jPanel3);

    jPanel4.setLayout(new java.awt.BorderLayout());

    org.openide.awt.Mnemonics.setLocalizedText(jLabel4, org.openide.util.NbBundle.getMessage(DistinguishedNameBuilderDialog.class, "DistinguishedNameBuilderDialog.jLabel4.text")); // NOI18N
    jLabel4.setPreferredSize(new java.awt.Dimension(100, 14));
    jPanel4.add(jLabel4, java.awt.BorderLayout.LINE_START);

    jTxtLocation.setText(org.openide.util.NbBundle.getMessage(DistinguishedNameBuilderDialog.class, "DistinguishedNameBuilderDialog.jTxtLocation.text")); // NOI18N
    jPanel4.add(jTxtLocation, java.awt.BorderLayout.CENTER);

    getContentPane().add(jPanel4);

    jPanel5.setLayout(new java.awt.BorderLayout());

    org.openide.awt.Mnemonics.setLocalizedText(jLabel5, org.openide.util.NbBundle.getMessage(DistinguishedNameBuilderDialog.class, "DistinguishedNameBuilderDialog.jLabel5.text")); // NOI18N
    jLabel5.setPreferredSize(new java.awt.Dimension(100, 14));
    jPanel5.add(jLabel5, java.awt.BorderLayout.LINE_START);

    jTxtState.setText(org.openide.util.NbBundle.getMessage(DistinguishedNameBuilderDialog.class, "DistinguishedNameBuilderDialog.jTxtState.text")); // NOI18N
    jPanel5.add(jTxtState, java.awt.BorderLayout.CENTER);

    getContentPane().add(jPanel5);

    jPanel6.setLayout(new java.awt.BorderLayout());

    org.openide.awt.Mnemonics.setLocalizedText(jLabel6, org.openide.util.NbBundle.getMessage(DistinguishedNameBuilderDialog.class, "DistinguishedNameBuilderDialog.jLabel6.text")); // NOI18N
    jLabel6.setPreferredSize(new java.awt.Dimension(100, 14));
    jPanel6.add(jLabel6, java.awt.BorderLayout.LINE_START);

    jTxtCountryCode.setText(org.openide.util.NbBundle.getMessage(DistinguishedNameBuilderDialog.class, "DistinguishedNameBuilderDialog.jTxtCountryCode.text")); // NOI18N
    jPanel6.add(jTxtCountryCode, java.awt.BorderLayout.CENTER);

    getContentPane().add(jPanel6);

    org.openide.awt.Mnemonics.setLocalizedText(jBtnCompleteDname, org.openide.util.NbBundle.getMessage(DistinguishedNameBuilderDialog.class, "DistinguishedNameBuilderDialog.jBtnCompleteDname.text")); // NOI18N
    jBtnCompleteDname.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jBtnCompleteDnameActionPerformed(evt);
      }
    });
    jPanel7.add(jBtnCompleteDname);

    getContentPane().add(jPanel7);

    setSize(new java.awt.Dimension(457, 258));
    setLocationRelativeTo(null);
  }// </editor-fold>//GEN-END:initComponents

  private void jBtnCompleteDnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCompleteDnameActionPerformed
    if (this.jTxtFullName.getText().trim().equals("")) {
      this.jTxtFullName.setText("Unknown");
    }
    if (this.jTxtOrganizationUnit.getText().trim().equals("")) {
      this.jTxtOrganizationUnit.setText("Unknown");
    }
    if (this.jTxtOrganization.getText().trim().equals("")) {
      this.jTxtOrganization.setText("Unknown");
    }
    if (this.jTxtLocation.getText().trim().equals("")) {
      this.jTxtLocation.setText("Unknown");
    }
    if (this.jTxtState.getText().trim().equals("")) {
      this.jTxtState.setText("Unknown");
    }
    if (this.jTxtCountryCode.getText().trim().equals("")) {
      this.jTxtCountryCode.setText("Unknown");
    }
    this.dname.setFullName(this.jTxtFullName.getText());
    this.dname.setOrganizationUnit(this.jTxtOrganizationUnit.getText());
    this.dname.setOrganization(this.jTxtOrganization.getText());
    this.dname.setLocation(this.jTxtLocation.getText());
    this.dname.setState(this.jTxtState.getText());
    this.dname.setCountryCode(this.jTxtCountryCode.getText());

    // Executes "windowClosing" event, which builds the dname parameter.
    WindowManager.closeWindow(this);
  }//GEN-LAST:event_jBtnCompleteDnameActionPerformed

  public Keystore.DistinguishedName getDname() {
    return dname;
  }

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
     * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(DistinguishedNameBuilderDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(DistinguishedNameBuilderDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(DistinguishedNameBuilderDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(DistinguishedNameBuilderDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>
    //</editor-fold>

    /* Create and display the dialog */
    EventQueue.invokeLater(new Runnable() {
      @Override
      public void run() {
        DistinguishedNameBuilderDialog dialog = new DistinguishedNameBuilderDialog(new javax.swing.JDialog());
        dialog.addWindowListener(new java.awt.event.WindowAdapter() {
          @Override
          public void windowClosing(java.awt.event.WindowEvent e) {
            System.exit(0);
          }
        });
        dialog.setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton jBtnCompleteDname;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JLabel jLabel6;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JPanel jPanel2;
  private javax.swing.JPanel jPanel3;
  private javax.swing.JPanel jPanel4;
  private javax.swing.JPanel jPanel5;
  private javax.swing.JPanel jPanel6;
  private javax.swing.JPanel jPanel7;
  private javax.swing.JTextField jTxtCountryCode;
  private javax.swing.JTextField jTxtFullName;
  private javax.swing.JTextField jTxtLocation;
  private javax.swing.JTextField jTxtOrganization;
  private javax.swing.JTextField jTxtOrganizationUnit;
  private javax.swing.JTextField jTxtState;
  // End of variables declaration//GEN-END:variables
}
