/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.netbeans.modules.signer.gui;

import java.awt.event.WindowEvent;
import java.util.Date;
import javax.swing.JOptionPane;
import org.netbeans.modules.signer.core.Keystore;
import org.netbeans.modules.signer.core.SecurityManager;
import org.netbeans.modules.signer.core.NBSignerOperationException;

/**
 * Keystore creator.
 *
 * @author elcocolio
 */
public class KeystoreCreatorDialog extends javax.swing.JDialog {

  private static int DAY = 24 * 60 * 60 * 1000; // 1 Day = 86400000 msecs.

  private Keystore tmpKs;

  /**
   * Creates new form KeystoreCreatorDialog
   *
   * @param dialog parent window.
   */
  public KeystoreCreatorDialog(javax.swing.JDialog dialog) {
    super(dialog, true);
    initComponents();
    this.setResizable(true);
    this.tmpKs = Keystore.createKeystore();
    this.tmpKs.setPathToModule(Keystore.getDefault().getPathToModule());
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jFchDirectoryChooser = new javax.swing.JFileChooser();
    jPanel2 = new javax.swing.JPanel();
    jLabel1 = new javax.swing.JLabel();
    jLbDistinguishedName = new javax.swing.JLabel();
    jBtnDistinguishedName = new javax.swing.JButton();
    jPanel1 = new javax.swing.JPanel();
    jLabel6 = new javax.swing.JLabel();
    jTxtKsName = new javax.swing.JTextField();
    jPanel7 = new javax.swing.JPanel();
    jTxtKsAlias = new javax.swing.JTextField();
    jLabel4 = new javax.swing.JLabel();
    jPanel3 = new javax.swing.JPanel();
    jLabel2 = new javax.swing.JLabel();
    jPwdKsPassword = new javax.swing.JPasswordField();
    jPanel4 = new javax.swing.JPanel();
    jLabel5 = new javax.swing.JLabel();
    jPanel5 = new javax.swing.JPanel();
    jDChValidity = new com.toedter.calendar.JDateChooser();
    jPanel6 = new javax.swing.JPanel();
    jBtnCreateKeystore = new javax.swing.JButton();

    jFchDirectoryChooser.setAcceptAllFileFilterUsed(false);
    jFchDirectoryChooser.setApproveButtonText(org.openide.util.NbBundle.getMessage(KeystoreCreatorDialog.class, "KeystoreCreatorDialog.jFchDirectoryChooser.approveButtonText")); // NOI18N
    jFchDirectoryChooser.setDialogTitle(org.openide.util.NbBundle.getMessage(KeystoreCreatorDialog.class, "KeystoreCreatorDialog.jFchDirectoryChooser.dialogTitle")); // NOI18N
    jFchDirectoryChooser.setFileSelectionMode(javax.swing.JFileChooser.DIRECTORIES_ONLY);

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    setTitle(org.openide.util.NbBundle.getMessage(KeystoreCreatorDialog.class, "KeystoreCreatorDialog.title")); // NOI18N
    getContentPane().setLayout(new java.awt.GridLayout(6, 2));

    jPanel2.setPreferredSize(new java.awt.Dimension(100, 500));
    jPanel2.setLayout(new java.awt.BorderLayout());

    org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(KeystoreCreatorDialog.class, "KeystoreCreatorDialog.jLabel1.text")); // NOI18N
    jLabel1.setPreferredSize(new java.awt.Dimension(124, 14));
    jPanel2.add(jLabel1, java.awt.BorderLayout.LINE_START);

    org.openide.awt.Mnemonics.setLocalizedText(jLbDistinguishedName, org.openide.util.NbBundle.getMessage(KeystoreCreatorDialog.class, "KeystoreCreatorDialog.jLbDistinguishedName.text")); // NOI18N
    jLbDistinguishedName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
    jPanel2.add(jLbDistinguishedName, java.awt.BorderLayout.CENTER);

    org.openide.awt.Mnemonics.setLocalizedText(jBtnDistinguishedName, org.openide.util.NbBundle.getMessage(KeystoreCreatorDialog.class, "KeystoreCreatorDialog.jBtnDistinguishedName.text")); // NOI18N
    jBtnDistinguishedName.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jBtnDistinguishedNameActionPerformed(evt);
      }
    });
    jPanel2.add(jBtnDistinguishedName, java.awt.BorderLayout.LINE_END);

    getContentPane().add(jPanel2);

    jPanel1.setLayout(new java.awt.BorderLayout());

    org.openide.awt.Mnemonics.setLocalizedText(jLabel6, org.openide.util.NbBundle.getMessage(KeystoreCreatorDialog.class, "KeystoreCreatorDialog.jLabel6.text")); // NOI18N
    jLabel6.setPreferredSize(new java.awt.Dimension(124, 14));
    jLabel6.setRequestFocusEnabled(false);
    jPanel1.add(jLabel6, java.awt.BorderLayout.LINE_START);

    jTxtKsName.setText(org.openide.util.NbBundle.getMessage(KeystoreCreatorDialog.class, "KeystoreCreatorDialog.jTxtKsName.text")); // NOI18N
    jPanel1.add(jTxtKsName, java.awt.BorderLayout.CENTER);

    getContentPane().add(jPanel1);

    jPanel7.setLayout(new java.awt.BorderLayout());

    jTxtKsAlias.setText(org.openide.util.NbBundle.getMessage(KeystoreCreatorDialog.class, "KeystoreCreatorDialog.jTxtKsAlias.text")); // NOI18N
    jPanel7.add(jTxtKsAlias, java.awt.BorderLayout.CENTER);

    org.openide.awt.Mnemonics.setLocalizedText(jLabel4, org.openide.util.NbBundle.getMessage(KeystoreCreatorDialog.class, "KeystoreCreatorDialog.jLabel4.text")); // NOI18N
    jLabel4.setPreferredSize(new java.awt.Dimension(124, 14));
    jLabel4.setRequestFocusEnabled(false);
    jPanel7.add(jLabel4, java.awt.BorderLayout.LINE_START);

    getContentPane().add(jPanel7);

    jPanel3.setLayout(new java.awt.BorderLayout());

    org.openide.awt.Mnemonics.setLocalizedText(jLabel2, org.openide.util.NbBundle.getMessage(KeystoreCreatorDialog.class, "KeystoreCreatorDialog.jLabel2.text")); // NOI18N
    jLabel2.setPreferredSize(new java.awt.Dimension(124, 14));
    jPanel3.add(jLabel2, java.awt.BorderLayout.LINE_START);

    jPwdKsPassword.setText(org.openide.util.NbBundle.getMessage(KeystoreCreatorDialog.class, "KeystoreCreatorDialog.jPwdKsPassword.text")); // NOI18N
    jPanel3.add(jPwdKsPassword, java.awt.BorderLayout.CENTER);

    getContentPane().add(jPanel3);

    jPanel4.setLayout(new java.awt.BorderLayout());

    org.openide.awt.Mnemonics.setLocalizedText(jLabel5, org.openide.util.NbBundle.getMessage(KeystoreCreatorDialog.class, "KeystoreCreatorDialog.jLabel5.text")); // NOI18N
    jLabel5.setPreferredSize(new java.awt.Dimension(124, 14));
    jPanel4.add(jLabel5, java.awt.BorderLayout.LINE_START);

    jPanel5.setLayout(new java.awt.BorderLayout());

    jDChValidity.setToolTipText(org.openide.util.NbBundle.getMessage(KeystoreCreatorDialog.class, "KeystoreCreatorDialog.jDChValidity.toolTipText")); // NOI18N
    jDChValidity.setDateFormatString(org.openide.util.NbBundle.getMessage(KeystoreCreatorDialog.class, "KeystoreCreatorDialog.jDChValidity.dateFormatString")); // NOI18N
    jPanel5.add(jDChValidity, java.awt.BorderLayout.CENTER);

    jPanel4.add(jPanel5, java.awt.BorderLayout.CENTER);

    getContentPane().add(jPanel4);

    org.openide.awt.Mnemonics.setLocalizedText(jBtnCreateKeystore, org.openide.util.NbBundle.getMessage(KeystoreCreatorDialog.class, "KeystoreCreatorDialog.jBtnCreateKeystore.text")); // NOI18N
    jBtnCreateKeystore.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jBtnCreateKeystoreActionPerformed(evt);
      }
    });
    jPanel6.add(jBtnCreateKeystore);

    getContentPane().add(jPanel6);

    setSize(new java.awt.Dimension(462, 215));
    setLocationRelativeTo(null);
  }// </editor-fold>//GEN-END:initComponents

  private int getValidity() throws NBSignerOperationException {
    int days = 0;
    Date now = new Date();
    Date date = this.jDChValidity.getDate();
    if (date != null) {
      if (date.before(now)) {
        throw new NBSignerOperationException(
                "Expiration date must be after today.\n"
                + "NOTE: this operation uses the system date\n"
                + "to validate the expiration date.");
      } else {
        long msecs = date.getTime() - now.getTime();
        days = msecs > 0 && msecs < DAY ? 1 : (int) Math.abs(msecs / DAY);
      }
    }
    return days;
  }

  private void jBtnCreateKeystoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCreateKeystoreActionPerformed
    try {
      String dname = this.jLbDistinguishedName.getText();
      String name = this.jTxtKsName.getText().trim();
      String alias = this.jTxtKsAlias.getText().trim();
      char[] pwd = this.jPwdKsPassword.getPassword();
      String password = pwd != null && pwd.length > 0 ? new String(pwd) : "";
      int days = this.getValidity();
      if (dname.equals("") || name.equals("") || alias.equals("") || password.equals("")) {
        throw new NBSignerOperationException("There are missing fields. Please verify.");
      } else {
        tmpKs.setName(name);
        tmpKs.setAlias(alias);
        tmpKs.setPassword(password);
        tmpKs.setValidity(days);
        SecurityManager.createKeystore(tmpKs);
        Keystore.setDefault(tmpKs);
      }
      JOptionPane.showMessageDialog(this, "Keystore has been successfully created!",
              "Netbeans Signer", JOptionPane.INFORMATION_MESSAGE);
      // It should assign new keystore name, alias and password on window closing.
      WindowManager.closeWindow(this);
    } catch (NBSignerOperationException ex) {
      JOptionPane.showMessageDialog(
              this, ex.getMessage(), "ERROR!", JOptionPane.ERROR_MESSAGE);
    }
  }//GEN-LAST:event_jBtnCreateKeystoreActionPerformed

  private void jBtnDistinguishedNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnDistinguishedNameActionPerformed
    WindowManager.showDistinguishedNameBuilder(this, new WindowClosingEventListener() {
      @Override
      public void handle(WindowEvent e) {
        DistinguishedNameBuilderDialog dnameDialog = (DistinguishedNameBuilderDialog) e.getWindow();
        jLbDistinguishedName.setText(dnameDialog.getDname().toString());
        tmpKs.getDistinguishedName().copy(dnameDialog.getDname());
      }
    });
  }//GEN-LAST:event_jBtnDistinguishedNameActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
     * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(KeystoreCreatorDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(KeystoreCreatorDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(KeystoreCreatorDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(KeystoreCreatorDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>
    //</editor-fold>

    /* Create and display the dialog */
    java.awt.EventQueue.invokeLater(new Runnable() {
      @Override
      public void run() {
        KeystoreCreatorDialog dialog = new KeystoreCreatorDialog(new javax.swing.JDialog());
        dialog.addWindowListener(new java.awt.event.WindowAdapter() {
          @Override
          public void windowClosing(java.awt.event.WindowEvent e) {
            System.exit(0);
          }
        });
        dialog.setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton jBtnCreateKeystore;
  private javax.swing.JButton jBtnDistinguishedName;
  private com.toedter.calendar.JDateChooser jDChValidity;
  private javax.swing.JFileChooser jFchDirectoryChooser;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JLabel jLabel6;
  private javax.swing.JLabel jLbDistinguishedName;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JPanel jPanel2;
  private javax.swing.JPanel jPanel3;
  private javax.swing.JPanel jPanel4;
  private javax.swing.JPanel jPanel5;
  private javax.swing.JPanel jPanel6;
  private javax.swing.JPanel jPanel7;
  private javax.swing.JPasswordField jPwdKsPassword;
  private javax.swing.JTextField jTxtKsAlias;
  private javax.swing.JTextField jTxtKsName;
  // End of variables declaration//GEN-END:variables
}
